Task 1: 
 
  1. 
 
Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [3]:
#let's see first what happens when 5 is divided by 0
x=5/0
print (x)

ZeroDivisionError: division by zero

In [4]:
#lets try above and catch the exception,so that we dont get any errors but do get the exception message that we print out
try:
    x=5/0
    print (x)
except: 
    print ("divide by 0 error")

divide by 0 error




2.
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 
 
Output should come as below: 
 
Americans  play Baseball. Americans  play Cricket. Americans  watch Baseball. Americans  watch Cricket. Indians play Baseball. Indians play Cricket. Indians watch Baseball. Indians watch Cricket. 

In [9]:
#declare subjects verbs and objects
subjects=["Americans","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"] 

for i in subjects:
    for j in verbs:
        for k in objects:
            print (i,j,k,'.')


Americans play Baseball .
Americans play Cricket .
Americans watch Baseball .
Americans watch Cricket .
Indians play Baseball .
Indians play Cricket .
Indians watch Baseball .
Indians watch Cricket .


Task 2:  
 
 
1.  
 
Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde. 

In [1]:
import  numpy as np 
def gen_vander_matrix(input_val, n, increasing=False):
    
    if not increasing:
        output_val = np.array([x**(n-1-i) for x in input_val for i in range(n)]).reshape(input_val.size,n)
    elif increasing:
        output_val = np.array([x**i for x in input_val for i in range(n)]).reshape(input_val.size,n)
    
    return output_val

print("------------OUTPUT-------------\n")

input_val = np.array([1,2,3,4,5])
n = 3
output_val_decreasing = gen_vander_matrix(input_val,n,False)
output_val_increasing = gen_vander_matrix(input_val,n,True)

print("The input array is:",input_val,"\n")
print("Number of columns in output matrix should be:",n,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",output_val_decreasing,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",output_val_increasing,"\n")

------------OUTPUT-------------

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

